### ISSUE TITLE
[BUG] "Invalid 'group': '--Deleted--'" error when restoring session

### ISSUE THREAD

**Issue by SlimShadyIAm** [rmagatti/auto-session#258] opened 2023-10-16 09:47 UTC
**Describe the bug**
When launching Neovim in a directory using `nvim`, I get the following error:

```
...hare/nvim/lazy/lazy.nvim/lua/lazy/core/handler/event.lua:169: Invalid 'group': '--Deleted--'

# stacktrace:
  - vim/_editor.lua:0
  - /auto-session/lua/auto-session/init.lua:659 _in_ **restore**
  - /auto-session/lua/auto-session/init.lua:721 _in_ **AutoRestoreSession**
  - ~/.config/nvim/lua/plugins/auto-session.lua:17
 ```

This didn't always happen but I am unsure of how to resolve this. 

**To Reproduce**
Dotfiles: https://github.com/SlimShadyIAm/dotfiles

1. Start neovim with auto-session installed
2.  See error like so:
<img width="853" alt="image" src="https://github.com/rmagatti/auto-session/assets/10660846/696f4237-7c97-43e6-b194-cfae4bbfbc2c">

**Expected behavior**
Session should restore with no error.

**Baseline (please complete the following information):**
 - Result of `set sessionoptions?`: ` sessionoptions=blank,buffers,curdir,folds,help,tabpages,winsize,terminal`
 - OS. e.g `uname -a`: `Darwin Aamirs-MacBook-Air.local 23.0.0 Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:34 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T8103 arm64`
 - Neovim version `nvim --version`: 0.9.4
 - URL to your current config (if public): https://github.com/SlimShadyIAm/dotfiles

**Comment by rmagatti** [comment] 2023-10-18 05:18
Can't reproduce. It looks like it's probably something related to your config, probably being corrupted. Perhaps try deleting your session and creating it again?

**Comment by SlimShadyIAm** [comment] 2023-10-27 12:06
I've tried deleting all the files under `~/.local/share/nvim/sessions/` and `~/.local/share/nvim/auto_session` and that didn't help. I've also tried doing a clean install of nvim. Do you have any suggestions for how I can trace this down? My friend is using a fork of my dotfiles and he has the same issue.

**Comment by rmagatti** [comment] 2023-10-27 19:38
If anything this looks more like a Lazy.nvim issue with your config than a session thing at all. You could try disabling auto session and sourcing a session file manually to see if you get a similar behaviour (which I don't think you will). You could also check what lazy.nvim us doing in that `event.lua` file and go from there.

I'm gonna close this issue for now as there's no evidence currently this has anything to do with auto-session. Feel free to reopen or open a new one if your debugging surfaces more evidence.

**Closed by rmagatti** 2023-10-27 19:38 UTC
Labels: bug
