### ISSUE TITLE
Auto save enabled doesn't work

### ISSUE THREAD

**Issue by shourov-rahman** [rmagatti/auto-session#275] opened 2024-03-12 19:58 UTC
I want to save session buffer automatically before exit nvim with `:wqa`. I enable `auto_save_enabled = true`. But It doesn't work. Here is my configuration.

```lua
return {
	"rmagatti/auto-session",
	config = function()
		local auto_session = require("auto-session")

		auto_session.setup({
			auto_save_enabled = true,
			auto_restore_enabled = false,
			auto_session_suppress_dirs = { "~/", "~/Dev/", "~/Downloads", "~/Documents", "~/Desktop/" },
		})

		local keymap = vim.keymap

		keymap.set("n", "<leader>wr", "<cmd>SessionRestore<CR>", { desc = "Restore session for cwd" }) -- restore last workspace session for current directory
		keymap.set("n", "<leader>ws", "<cmd>SessionSave<CR>", { desc = "Save session for auto session root dir" }) -- save workspace session for current working directory
	end,
}
```

**Comment by rmagatti** [comment] 2024-03-31 05:27
Can you still reproduce if you don't pass these two options at startup?
```lua
auto_save_enabled = true,
auto_restore_enabled = false,
```

**Comment by rmagatti** [comment] 2024-04-01 20:57
`cd` changes the `cwd` for the whole Neovim instance. `:h cd`. You can probably try `:h lcd` or `:h tcd` instead. Auto session runs `getcwd()` so whatever that returns is what it'll try to operate on.

**Comment by andrevmatos** [comment] 2024-04-01 22:12
I usually change cwd through NeoTree, which probably do one of the others, as I can see different `:pwd` on each tab. Nonetheless, this still seems to mess with auto-save (a previously/explicitly saved session).

**Comment by steakhutzeee** [comment] 2024-04-07 14:37
I noticed that `:SessionSave` works, but without it does not work.

Looking into the session file I see to ref to the opened file but only to the dir.

**Comment by rmagatti** [comment] 2024-04-14 04:38
> Can you still reproduce if you don't pass these two options at startup?
> 
> ```lua
> auto_save_enabled = true,
> auto_restore_enabled = false,
> ```

My question is the same still, what happens if you don't pass these options at all? (they are already the default)
I suspect something might be wrong with the handling of when these are set manually.

**Comment by steakhutzeee** [comment] 2024-04-14 09:05
I'm actually using https://github.com/Shatur/neovim-session-manager

Actually from the docs I see that the 2 values have nil as default value. That's why I set the options up in the first place.

**Comment by wonrax** [comment] 2024-05-07 02:42
> > Can you still reproduce if you don't pass these two options at startup?
> > ```lua
> > auto_save_enabled = true,
> > auto_restore_enabled = false,
> > ```
> 
> My question is the same still, what happens if you don't pass these options at all? (they are already the default) I suspect something might be wrong with the handling of when these are set manually.

It still won't autosave with the two options unset, here's my config:
```lua
return {
  {
    'rmagatti/auto-session',
    config = function()
      vim.o.sessionoptions = 'blank,buffers,curdir,folds,help,tabpages,winsize,winpos,terminal,localoptions'

      require('auto-session').setup {
        log_level = 'info',
        auto_session_enable_last_session = true,
        auto_session_root_dir = vim.fn.stdpath 'data' .. '/sessions/',
        auto_session_enabled = true,
        -- auto_save_enabled = true,
        -- auto_restore_enabled = false,
        auto_session_suppress_dirs = nil,
        auto_session_use_git_branch = nil,
        -- the configs below are lua only
        bypass_session_save_file_types = nil,
      }
    end,
    lazy = false,
  },
}
```

**Comment by rmagatti** [comment] 2024-05-14 21:39
@wonrax can you set `log_level=vim.log.levels.DEBUG` and paste in the results of starting neovim stopping/starting when you expect a session to be loaded or saved automatically?

**Comment by wonrax** [comment] 2024-05-15 03:28
I don't know how to pause to get the messages when doing neovim quit all, but session autoload works fine when I have manually created a save before. It just won't autosave on neovim quit.

**Comment by andrevmatos** [comment] 2024-06-03 10:09
Yes, I see `getcwd` usage is quite widespread in the code, but that can be undesired in a scenario where user `tcd` and `lcd` in different directories per tab (sometimes, without a tab remaining in the original directory), and `getcwd` always return the current cwd instance (local, tab or global).
IMO the _expected_ approach would be that only global `cwd` is used to pick current session to load or save, even if user tcd'ed to different directories in all tabs.

**Comment by cameronr** [comment] 2024-07-04 05:58
@wonrax you can run the autosaving logic without exiting using this command 

`:lua require('auto-session').AutoSaveSession()`

Then you should be able to check the messages via `:messages` (or `:Notifications` if you use something like `nvim-notify`)

**Comment by sakithb** [comment] 2024-08-22 09:14
I had the same issue. My projects folder is symlinked from `/mnt/projects` to `~/projects`, and I had `auto_session_allowed_dirs` set to `{ "~/projects/*" }`. Changing it to `{ "/mnt/projects/*" }` worked for me.

**Comment by cameronr** [comment] 2024-08-22 21:49
@sakithb Ah, interesting. I think we can fix it so symlinks will match. I'll take a look.

Is anyone else in this thread still having problems with auto-saving? The code has changed a lot since the original issue so I want to see if anyone is still having trouble.

**Comment by DUOLabs333** [comment] 2024-08-26 03:33
I just tried out this library and I have the same problem --- launching nvim creates the session, but autosave/autoreload will not work for that directory unless I run `:SessionSave` at least once in the directory (I have to repeat this process for every directory I want to create a session for).

**Comment by DUOLabs333** [comment] 2024-08-26 03:42
Never mind, I saw what the problem was --- I was testing it out by doing `nvim file.txt; nvim`. However, according to the README, the whole auto-session machinery is disabled when a file is specified, so of course nothing got saved. Doing (`nvim`, `:edit file.txt`, `:qa!`, `nvim`) works as expected.

This also explains why `:SessionSave` was seemingly necessary to "kickstart" the autosave process --- without it, the only session that would be loaded was the empty session.

**Comment by cameronr** [comment] 2024-08-27 22:38
@sakithb 
> I had the same issue. My projects folder is symlinked from `/mnt/projects` to `~/projects`, and I had `auto_session_allowed_dirs` set to `{ "~/projects/*" }`. Changing it to `{ "/mnt/projects/*" }` worked for me.

The code to support symlinks is now pushed so this should now work. If you test it, let me know!

**Comment by rmagatti** [comment] 2024-08-28 16:29
Closing. Can re-open if needed

**Closed by rmagatti** 2024-08-28 16:29 UTC

**Comment by sakithb** [comment] 2024-08-30 15:08
It works now!
