### ISSUE TITLE
Unexpected behaviour when opening session with nvim-tree

### ISSUE THREAD

**Issue by brapifra** [rmagatti/auto-session#50] opened 2021-08-14 06:21 UTC
Hey!

First of all, congrats on the plugin :)

Unfortunately, I encounter this `E95: Buffer with this name already exists` error when opening nvim after closing it with `nvim-tree` open:
![image](https://user-images.githubusercontent.com/17855450/129436153-919188cc-2824-4690-b8ed-b04c68f9ead7.png)

Not sure if it's something that needs to be fixed on your end or on nvim-tree's end though. Let me know!

**Comment by rmagatti** [comment] 2021-08-14 17:40
Hey @brapifra I'm guessing this is because an nvim-tree buffer doesn't support being saved on a session, at least with your current sessionopts.

I don't use nvim-tree so I wouldn't know much further than that. What I can tell you is that this plugin merely wraps `mksession` functionality, so I doubt it's something I could fix on my end.

That being said, what I've seen people do is use the session hooks to close any tree-like plugin's windows before saving the session so you at least don't see what you're currently seeing.

I hope that helps at least a bit 😄

**Comment by brapifra** [comment] 2021-08-14 17:49
Thanks for the info @rmagatti!
Makes sense, I'll give that a try :)

**Comment by sujaybokil** [comment] 2021-08-17 13:49
Hii @brapifra, I had the same issue which I solved through hooks and I will leave my config down here for you which would solve it hopefully. Adding the last 2 options (which are hooks) would take care of the issue.

```
local opts = {
  log_level = 'info',
  auto_session_enable_last_session = false,
  auto_session_root_dir = vim.fn.stdpath('data').."/sessions/",
  auto_session_enabled = false,
  auto_save_enabled = false,
  auto_restore_enabled = false,
  auto_session_suppress_dirs = nil,
  pre_save_cmds = {"tabdo NvimTreeClose"},
  post_restore_cmds = {"tabdo NvimTreeRefresh"}
}

require('auto-session').setup(opts)
```

**Comment by brapifra** [comment] 2021-08-17 13:59
Hey @sujaybokil 
For some reason, I can't make your config working on my neovim. I did this and it works like a charm:
```lua
    use {
      "rmagatti/auto-session",
      config = function()
        require("auto-session").setup {
          pre_save_cmds = {"NvimTreeClose"}
        }
      end
    }
```

**Comment by rmagatti** [comment] 2021-08-23 16:45
Closing since it looks like hooks cover the necessary cases.

**Closed by rmagatti** 2021-08-23 16:45 UTC

**Comment by mattleong** [comment] 2021-12-03 20:13
```lua
pre_save_cmds = {"NvimTreeClose"}
```

Can open a new issue if needed. But this hook alone doesn't properly seem to close nvim-tree anymore. Can anyone else verify?

**Comment by egidijusz** [comment] 2021-12-04 10:24
> ```lua
> pre_save_cmds = {"NvimTreeClose"}
> ```
> 
> Can open a new issue if needed. But this hook alone doesn't properly seem to close nvim-tree anymore. Can anyone else verify?

I can confirm.

**Comment by rmagatti** [comment] 2021-12-06 04:44
Hey guys, so unless there's an issue with the hook itself, this is probably something on the nvim-tree side of things. Let me know if I can help with anything though!

**Comment by r7vme** [comment] 2021-12-11 08:29
Works for me

```
let g:auto_session_pre_save_cmds = [":lua require'nvim-tree'.setup() | tabdo NvimTreeClose"]
```

**Comment by im-n1** [comment] 2022-01-10 10:35
> 



> Works for me
> 
> ```
> let g:auto_session_pre_save_cmds = ["lua require'nvim-tree'.setup() | tabdo NvimTreeClose"]
> ```

Cannot confirm on nvim 0.5

**Comment by r7vme** [comment] 2022-01-10 10:51
Actually seems smth was updated, and today with newer neovim or plugins I fixed it to smth like

```
let g:auto_session_pre_save_cmds = ["lua require'nvim-tree'.setup()", "tabdo NvimTreeClose"]
```

**Comment by im-n1** [comment] 2022-01-11 09:56
still no luck

**Comment by timtyrrell** [comment] 2022-01-11 15:32
On neovim nightly.... 

This does not work:
```
require('auto-session').setup {
  -- other config above
  pre_save_cmds = {"tabdo NvimTreeClose"}
}
```

This works:
```
require('auto-session').setup {
  -- other config above
  pre_save_cmds = {"lua require'nvim-tree'.setup()", "tabdo NvimTreeClose"}
}
```

_"Works" means if I close neovim with a nvim-tree buffer open, when I reopen vim, that buffer is gone and not open_
