### ISSUE TITLE
[BUG] Session does not get sourced if file in session is open in another Neovim instance

### ISSUE THREAD

**Issue by melkster** [rmagatti/auto-session#117] opened 2022-02-19 14:15 UTC
**Describe the bug**
auto-sessions throws an error if I open a session containing a file that's already open in another Neovim instance.

My guess is that this is related to [this issue](https://github.com/neovim/neovim/issues/17397) where Neovim gives the `ATTENTION Found a swap file by the name...` even if `shortmess+=A` is set.

However it seems that auto-session doesn't recover from this, since even if I press "Edit anyway" the session still doesn't get restored properly restored, and auto-session itself also throws additional errors.

This is the error message:

```txt
.../nvim/packages/auto-session/lua/auto-session-library.lua:189:         Error restoring session! The session might be corrupted.
Disabling auto save. Please check for errors in your config. Error:

Vim(edit):E325: ATTENTION
stack traceback:
^I[C]: in function 'error'
^I.../nvim/packages/auto-session/lua/auto-session-library.lua:189: in function 'error'
^I.../.config/nvim/packages/auto-session/lua/auto-session.lua:327: in function 'restore'
^I.../.config/nvim/packages/auto-session/lua/auto-session.lua:353: in function 'RestoreSession'
^I.../.config/nvim/packages/auto-session/lua/auto-session.lua:290: in function <.../.config/nvim/packages/auto-session/lua/auto-session.lua:288>
```

**To Reproduce**

1. Use the following config file `config.vim`:

   ```vim
   call plug#begin('~/.config/nvim/packages/')
   Plug 'rmagatti/auto-session'
   call plug#end()

   set shortmess+=A

   lua << EOF
   require('auto-session').setup()
   EOF
   ```

2. `nvim -u config.vim testfile.txt`
3. `split testfile2.txt`
4. `SaveSession`
5. (in a new shell) `nvim -u config.vim`
6. Neovim throws "Found a swap file" error, press `e` as in "Edit anyway"
7. `RestoreSession testfile.txt`
8. Neovim throws "Found a swap file", press `e`
9. auto-session throws error and session isn't properly restored

**Expected behavior**

Neovim properly restores the session without any errors

**Baseline (please complete the following information):**

- Result of `set sessionoptions?`: `blank,buffers,curdir,folds,help,tabpages,winsize`
- OS. e.g `uname -a`: `Linux 5.13.19-2-MANJARO #1 SMP PREEMPT Sun Sep 19 21:31:53 UTC 2021 x86_64 GNU/Linux`
- Neovim version `nvim --version`: `NVIM v0.7.0-dev+1027-gf02a5a7bd`
- URL to your current config (if public): https://github.com/Melkster/nvim/

**Comment by rmagatti** [comment] 2022-02-20 07:28
Hey @melkster thanks for the submission!

So this is technically not a bug as far as I can tell, auto-session for the purposes of trying to not corrupt your session disables the automatic saving of a session upon trying to restore one `source session_name.vim` and that throwing an error. The reasoning for this is you might have had a valid session before but changed a config value that broke your config and tried restoring the session only to then save it with potentially broken settings.

Now in this particular case what happens is Neovim is throwing that error about swap files when the session is attempting to be restored, that erroring out just makes auto-session's Restore function exit early.
```lua
if not success then
  Lib.logger.error([[
    Error restoring session! The session might be corrupted.
    Disabling auto save. Please check for errors in your config. Error: 
  ]] .. result)
  AutoSession.conf.auto_save_enabled = false
  return
end
```

The part that could be changed here is you end you seeing errors thrown by auto session because of how the error log works (it just uses `error(msg)`). But otherwise I think the issue you opened with Neovim is indeed the way to go for the session actually being able to restore.

**Comment by melkster** [comment] 2022-02-22 07:50
I see. Thanks for your response. Guess that I'll have to wait for the upstream issue to be fixed then before I can use auto-session :)

**Comment by rmagatti** [comment] 2022-02-22 20:18
I'm sure you've considered this but another option is to not use swap files (I have `set noswap` myself). Adding a config to bypass the auto-session specific behaviour could also be done but wouldn't really solve your problem unfortunately if you still want swap files.

**Comment by melkster** [comment] 2022-02-22 21:03
That's true I guess that's an option and to be fair I do save files a _lot_ when editing, but it the thought of not having my files backed up while editing also makes me kinda nervous.

**Comment by rmagatti** [comment] 2022-02-23 03:58
Hasn't ever really been an issue for me but I understand 👍.

And yeah unfortunately auto-session can't really fix this itself - let's see if the Neovim issue you opened gets some traction.

**Comment by rmagatti** [comment] 2022-05-20 16:25
Fixed by https://github.com/neovim/neovim/pull/18636

**Closed by rmagatti** 2022-05-20 16:25 UTC
Labels: bug
